# Generated by Django 5.0.4 on 2024-04-10 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(choices=[('san_fernando_pos', 'San Fernando - POS'), ('pos_san_fernando', 'POS - San Fernando')], max_length=100)),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('mechanical', 'Mechanical Emergency'), ('fire', 'Fire'), ('collision_grounding', 'Collision or Grounding'), ('man_overboard', 'Man Overboard')], max_length=100)),
                ('date_occured', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('comments', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
