# Generated by Django 5.0.4 on 2024-04-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_ticket_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='trip',
            field=models.CharField(choices=[('one_way', 'One Way'), ('return', 'Return')], default='one_way', max_length=20),
            preserve_default=False,
        ),
    ]
