# Generated by Django 5.0.4 on 2024-04-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
