# Generated by Django 5.0.4 on 2024-04-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ticket_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
