# Generated by Django 5.0.4 on 2024-04-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_emergency_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
