# Generated by Django 5.0.4 on 2024-04-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_emergency_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
